const EVENT_TYPES = {
  TIMER_STARTED: "TIMER_STARTED",
  TIMER_EXPIRED: "TIMER_EXPIRED",
  AUTO_SUBMIT: "AUTO_SUBMIT",
  TAB_SWITCH: "TAB_SWITCH",
  FOCUS_LOST: "FOCUS_LOST",
  COPY_ATTEMPT: "COPY_ATTEMPT",
  PASTE_ATTEMPT: "PASTE_ATTEMPT",
  FULLSCREEN_EXIT: "FULLSCREEN_EXIT",
  TAB_HIDDEN: "TAB_HIDDEN",
  TAB_VISIBLE: "TAB_VISIBLE",
  TEST_SUBMITTED: "TEST_SUBMITTED",
  WARNING_THRESHOLD_REACHED: "WARNING_THRESHOLD_REACHED",
  RIGHT_CLICK_BLOCKED: "RIGHT_CLICK_BLOCKED",
  DEVTOOLS_ATTEMPT: "DEVTOOLS_ATTEMPT",
  VIOLATION_LIMIT_REACHED: "VIOLATION_LIMIT_REACHED",
  KEYBOARD_SHORTCUT_BLOCKED: "KEYBOARD_SHORTCUT_BLOCKED",
};

module.exports = EVENT_TYPES;
